on:
  push:
    branches:
      - master
jobs:
  build:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Deploy code to Lambda
      uses: ovsen/action-deploy-aws-lambda@1.2
      with:
        lambda_function_name: 'river-levels'
        lambda_region: 'eu-north-1'
